# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Test image generation

on:
  workflow_call: # This makes the workflow reusable

jobs:
  build_images:
    if: github.repository == 'open-telemetry/opentelemetry-demo'
    uses: ./.github/workflows/component-build-images.yml
