# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: End-End Code Deployment pipeline

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the workflow

jobs:
  build_test_images:
    uses: ./.github/workflows/component-build-images.yml
    secrets: inherit

  # run_tests:
  #   needs: build_images
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v3

  #     - name: Set up Docker
  #       uses: docker/setup-buildx-action@v3

  #     - name: Test Image generation
  #       run: make run-tests  # Or use docker compose run frontendTests etc.
  kubenetes_deployment:
    uses: ./.github/workflows/kubernetes-deployment.yml
    needs: build_test_images
    secrets: inherit
  
