# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: End-End Code Deployment pipeline

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the workflow

jobs:
  build_images:
    uses: ./.github/workflows/component-build-images.yml
    secrets: inherit

  # integration_checks:
  #   uses: ./.github/workflows/checks.yml
  #   needs: build_images
  #   secrets: inherit
  # integration_tests:
  #   uses: ./.github/workflows/run-integration-tests.yml
  #   needs: build_images
  #   secrets: inherit
  kubenetes_deployment:
    uses: ./.github/workflows/kubernetes-deployment.yml
    needs: build_images
    secrets: inherit
  
