# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: End-End Code Deployment pipeline

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the workflow

jobs:
  build_test_images:
    uses: ./.github/workflows/component-build-images.yml
    secrets: inherit

  run_tests:
    name: Run Integration Tests
    needs: build_test_images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Integration Tests
        run: |
          docker compose -f docker-compose.yml -f docker-compose-tests.yml up -d frontendTests traceBasedTests
        continue-on-error: true  # Allow pipeline to continue even if tests fail

  kubenetes_deployment:
    uses: ./.github/workflows/kubernetes-deployment.yml
    needs: run_tests
    secrets: inherit
  
