# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: End-End Code Deployment pipeline

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the workflow

jobs:
  build_test_images:
    uses: ./.github/workflows/component-build-images.yml
    secrets: inherit

  run_tests:
    name: Run Integration Tests
    needs: build_test_images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Integration Tests
        run: |
          docker-compose -f docker-compose.yml -f test.yml up --exit-code-from integrationTests
        continue-on-error: true  # Allow pipeline to continue even if tests fail

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 7

  kubenetes_deployment:
    uses: ./.github/workflows/kubernetes-deployment.yml
    needs: run_tests
    secrets: inherit
  
